### ISSUE TITLE
'Unable to detect content-type for .hdr' fails action

### ISSUE THREAD

**Issue by btutal** [badsyntax/github-action-aws-s3#332]
Is it on purpose that action fails when `content-type` is not detected and what is the recommended way to sync such files?

**Comment by badsyntax** [comment]
Not on purpose! 

This package uses https://github.com/jshttp/mime-types to detect mime/content types.  I'd expect it to support detecting mime type for hdr files. 

Can you post a screenshot of the error you're seeing?

**Comment by badsyntax** [comment]
I'll do some testing with hdr files, thanks for the bug report.

**Comment by btutal** [comment]
> I'll do some testing with hdr files, thanks for the bug report.

Did you have a chance to test it with her files?

**Comment by badsyntax** [comment]
Hi, sorry for the long delay, i've just been very busy with my day job :( 

I've released support for .hdr files with https://github.com/badsyntax/github-action-aws-s3/pull/333

Please let me know if there are any problems.
